'''
Simple QA-Pipeline
'''
# ================================
# Imports
# ================================
from typing import TypedDict
from langgraph.graph import StateGraph, START, END
from langchain_ollama import ChatOllama

# ================================
# Initialize Local LLM (Ollama)
# ================================
model = ChatOllama(
    model="llama3.1:8b",   
    temperature=0
)

# ================================
# Define State
# ================================
class LLMState(TypedDict):
    question: str
    answer: str


# ================================
# Define Node
# ================================
def llm_qa(state: LLMState) -> dict:
    question = state["question"]

    prompt = f"Answer the following question: {question}"

    response = model.invoke(prompt)

    return {"answer": response.content}


# ================================
# Build Graph
# ================================
builder = StateGraph(LLMState)

builder.add_node("llm_qa", llm_qa)

builder.add_edge(START, "llm_qa")
builder.add_edge("llm_qa", END)

graph = builder.compile()


# ================================
# Execute
# ================================
initial_state = {
    "question": "How far is the Moon from Earth?",
    "answer": ""
}

result = graph.invoke(initial_state)

print(result)


"""
LangGraph + LLM (Ollama) QA Pipeline

Purpose
-------
Build a simple AI pipeline where:
Input question → LLM → Answer → Output

This shows how LangGraph integrates with an LLM.


------------------------------------------------------------
1️⃣ State (Shared Data Structure)
------------------------------------------------------------

class LLMState(TypedDict):
    question: str
    answer: str

• This is the data flowing through the graph
• question → input from user
• answer → generated by LLM

Think:
State = "memory" shared across steps


------------------------------------------------------------
2️⃣ LLM Initialization
------------------------------------------------------------

model = ChatOllama(
    model="llama3.1:8b",
    temperature=0
)

• Uses local Ollama model
• temperature=0 → deterministic output (less randomness)
• Good for factual Q&A


------------------------------------------------------------
3️⃣ Node → llm_qa
------------------------------------------------------------

def llm_qa(state):
    question = state["question"]
    prompt = f"Answer the following question: {question}"
    response = model.invoke(prompt)
    return {"answer": response.content}

What happens:

• Reads → question
• Builds prompt
• Calls LLM
• Returns → answer

Important:
✔ Returns only {"answer": ...}
✔ LangGraph merges into state


------------------------------------------------------------
4️⃣ Graph Construction
------------------------------------------------------------

builder = StateGraph(LLMState)

builder.add_node("llm_qa", llm_qa)

builder.add_edge(START, "llm_qa")
builder.add_edge("llm_qa", END)

Flow:
START → llm_qa → END

• Single-node pipeline
• Minimal but real-world pattern


------------------------------------------------------------
5️⃣ Execution
------------------------------------------------------------

initial_state = {
    "question": "...",
    "answer": ""
}

result = graph.invoke(initial_state)

Execution steps:

1. Input enters graph
2. llm_qa node runs
3. Answer is generated
4. Final state returned


------------------------------------------------------------
6️⃣ Final Output Structure
------------------------------------------------------------

{
    "question": "How far is the Moon from Earth?",
    "answer": "Approximately 384,400 km"
}

• Original input preserved
• New data added by node


------------------------------------------------------------
7️⃣ Key Concepts
------------------------------------------------------------

✔ State → carries data across nodes  
✔ Node → does one task (LLM call here)  
✔ Edge → defines execution flow  
✔ Partial updates → only return changed fields  


------------------------------------------------------------
8️⃣ Why This Matters
------------------------------------------------------------

This is the foundation of real AI systems:

• Multi-step reasoning pipelines
• Tool calling agents
• Retrieval + generation (RAG)

Instead of:
❌ one big function

You get:
✔ modular steps
✔ clean data flow
✔ scalable architecture


------------------------------------------------------------
Key Takeaway
------------------------------------------------------------

LangGraph wraps LLM calls into structured pipelines:

Input → Node (LLM) → Output

This makes AI systems predictable, testable, and composable.
"""